version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mcp-filesystem-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    binary: mcp-filesystem-server
    main: .

archives:
  - id: default
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Using new snapshot configuration
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mark3labs
    name: mcp-filesystem-server
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"
  mode: replace
